# Generated by Django 4.2 on 2023-06-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome', max_length=50)),
                ('ano', models.IntegerField(default=0)),
                ('semestre', models.IntegerField(default=0)),
                ('ects', models.IntegerField(default=0)),
                ('topicos', models.CharField(blank=True, default='Topicos', max_length=500)),
                ('ranking', models.IntegerField(blank=True, default=0)),
                ('pagina', models.CharField(default='Sem link', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Titulo', max_length=100)),
                ('descricao', models.CharField(blank=True, default='Descrição', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Titulo', max_length=100)),
                ('descricao', models.CharField(default='Descrição', max_length=500)),
                ('fotografia', models.ImageField(blank=True, upload_to='')),
                ('link', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome', max_length=100)),
                ('cargo', models.CharField(blank=True, default='Sem cargo', max_length=50)),
                ('lusofona', models.CharField(blank=True, default='Sem link', max_length=300)),
                ('linkedin', models.CharField(blank=True, default='Sem link', max_length=300)),
                ('cadeira', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.cadeira')),
            ],
        ),
        migrations.CreateModel(
            name='Tfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Titulo', max_length=100)),
                ('ano', models.IntegerField(default=0)),
                ('resumo', models.CharField(default='Sumario', max_length=500)),
                ('relatorio', models.CharField(default='Sem link', max_length=300)),
                ('github', models.CharField(blank=True, default='Sem link', max_length=300)),
                ('pessoas', models.ManyToManyField(blank=True, to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Titulo', max_length=100)),
                ('descricao', models.CharField(default='Descrição', max_length=500)),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('ano', models.IntegerField(default=0)),
                ('github', models.CharField(blank=True, default='Sem link', max_length=300)),
                ('cadeira', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.cadeira')),
                ('competencias', models.ManyToManyField(blank=True, to='portfolio.competencia')),
                ('participantes', models.ManyToManyField(blank=True, to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Titulo', max_length=100)),
                ('descricao', models.CharField(default='Descrição', max_length=500)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('fotografia', models.ImageField(blank=True, upload_to='')),
                ('autor', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='competencias',
            field=models.ManyToManyField(blank=True, to='portfolio.competencia'),
        ),
    ]
